unzipfile <- unzip("exdata%2Fdata%2Fhousehold_power_consumption.zip")
dataset <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")

dataset$Global_active_power <- as.numeric(as.character(dataset$Global_active_power))
newdata1 <- subset(dataset, Date == '1/2/2007')
newdata2 <- subset(dataset, Date == '2/2/2007')
fevdata <- rbind(newdata1, newdata2)
fevdata$Date <- as.Date(fevdata$Date, format = "%d/%m/%Y")
##fevdata$dayweek <- weekdays(fevdata$Date)
##fevdata$dayweek <- as.factor(fevdata$dayweek)
fevdata2 <- transform(fevdata, datetime = interaction(Date, Time, sep=' '))
fevdata2$datetime <- strptime(fevdata2$datetime, "%Y-%m-%d %H:%M:%S")
plot(fevdata2$datetime, fevdata2$Global_active_power, type = 'l', ylab = 'Global Active Power (kilowatts)', xlab = '')
dev.copy(png, file = "plot2.png")
dev.off()